### PR TITLE
Merge `neo` branch into `v14.x.x`

### PR DESCRIPTION
**Pull request by david-eckardt-sociomantic**

### CODE REVIEW

**Comment by gavin-norman-sociomantic** [comment]
Couple of minor-looking build errors with dmd 2.071.2.

**Comment by david-eckardt-sociomantic** [comment]
Fixed the build errors. However, one is in swarm so this is now blocked, depending on swarm v5.0.3, see https://github.com/sociomantic-tsunami/swarm/pull/285.

**Comment by david-eckardt-sociomantic** [comment]
Updated to swarm v5.0.3, green.

**Review by gavin-norman-sociomantic — APPROVED** [review]

**Comment by gavin-norman-sociomantic** [comment]
@david-eckardt-sociomantic please push to upstream. (Can't be merged from the github UI.)

**Comment by david-eckardt-sociomantic** [comment]
Pushed to upstream.

**Pull request closed without merging**
