### PR TITLE
Pass the request resources to abstract methods in node requests

### PR DESCRIPTION
**Pull request by david-eckardt-sociomantic**
The dmqnode implementations of these methods need them.

### CODE REVIEW

**Comment by gavin-norman-sociomantic** [comment]
Wouldn't it be easier to store the shared resources as a class field? As far as I remember, that was the intention. (It's actually how things were before we started messing around with changing the way node requests are handled.)

**Comment by gavin-norman-sociomantic** [comment]
Right, yeah, the `resources` field was removed recently. For example, in the Push request:
* `resources` used to be stored here: https://github.com/sociomantic-tsunami/dmqproto/commit/960fbef4d9f15a7d16945f3cf1ca5e3ecc3a0c74#diff-c1081cac7395e3f89ee8e1e2c110a722L37
* and passed to the request handler's ctor here: https://github.com/sociomantic-tsunami/dmqproto/commit/960fbef4d9f15a7d16945f3cf1ca5e3ecc3a0c74#diff-a596055fe89b61ecd8d26e4c3af97b90L54

So the change should be that, rather than receiving the shared resources in the request handler's ctor, it's received via `handle`. This will mean that derived code (the fake and real DMQ implementations) won't need to be changed.

**Comment by nemanja-boric-sociomantic** [comment]
The reason against storing the `resources` field there is the same as we're not exposing `resources` from the `IRequestHandler` as protected, but private - it wouldn't be clear that the lifetime would be tied to the lifetime of the request's `handle` method (I've been told - I wasn't here - that that was the actual review comment why the `IRequstHandler.resources` were made private (they were originally made `protected`). Moving just the storing of the resources in the request implementation just moves this problem (if it's really a problem), IMHO.

Btw, changing the dmqproto code is (still) completely allowed as we haven't released v14.1.0 yet :angel:

**Comment by david-eckardt-sociomantic** [comment]
In addition to @nemanja-boric-sociomantic's comment making `resources` `protected` would make passing it as a parameter of `handle` unnecessary, but removing it there would be a breaking change.

**Comment by david-eckardt-sociomantic** [comment]
For clarity, limiting the scope of `connection` and `resources` is technically not required but IMHO adds clarity, they should be used only in `handle` (actually `pre/postSupportedCodeSent`).

**Comment by gavin-norman-sociomantic** [comment]
>The reason against storing the resources field there is the same as we're not exposing resources from the IRequestHandler as protected, but private

This is what I don't understand. `IRequestHandler` is an interface, so doesn't have any fields...?

**Comment by david-eckardt-sociomantic** [comment]
This is about [`IRequestHandlerRequest`](https://github.com/sociomantic-tsunami/dmqproto/blob/v14.x.x/src/dmqproto/node/neo/request/core/IRequestHandlerRequest.d) in dmqproto. 
But now @nemanja-boric-sociomantic and I noticed changing the signature of `handle` would not be a breaking change because it has not been released so far.

**Comment by gavin-norman-sociomantic** [comment]
Ahh. Puh. What happened to the change in swarm that moved back from the pre/post supported code methods to a single `handle` again?

**Comment by david-eckardt-sociomantic** [comment]
This is https://github.com/sociomantic-tsunami/swarm/pull/279, released in swarm v5.1. I can't use that swarm version for dmqproto v14.1. But passing connection, resources and payload to subclasses as function parameters  instead of `protected` members of `IRequestHandlerRequest` the dmqproto code will be close to how things work with swarm v5.1.

**Comment by gavin-norman-sociomantic** [comment]
Ahh I see where the confusion is coming from now. I have been aiming at it working like this: https://github.com/gavin-norman-sociomantic/swarm/blob/93c63204f5c3e19deac3a5c7607c161aadcb25be/integrationtest/neo/node/request/DoublePut.d.

dhtproto also works this way.

dmqproto is going down a different path, due to the changes made in https://github.com/sociomantic-tsunami/dmqproto/pull/36/commits/8adbeeac409ed2b19154ce3528b9e8612b93f575.

I'm not sure what dlsproto is doing. (Or if it's not been adapted to this yet.)

It'd be advantageous to get everything structured in a consistent way, I think.

**Comment by nemanja-boric-sociomantic** [comment]
`dlsproto` is not adapted yet, I would rather wait for this to clear up.

**Comment by gavin-norman-sociomantic** [comment]
> I have been aiming at it working like this

Gah, this is for swarm v5.1.0, though :( What a mess.

**Comment by nemanja-boric-sociomantic** [comment]
> dhtproto also works this way.

This is possible for dhtproto which still doesn't have neo in the semver branch, but this is not possible for dmqproto (and it will not be possible for dlsproto as well) without releasing new major, since you're using `IRequest` which is added in 5.1.0

**Comment by gavin-norman-sociomantic** [comment]
The thing I don't like (and I should have said this in https://github.com/sociomantic-tsunami/dmqproto/commit/8adbeeac409ed2b19154ce3528b9e8612b93f575) is the addition of this abstract class (`IRequestHandlerRequest`). Our request handlers have been deliberately hierarchy-free until now.

>For clarity, limiting the scope of `connection` and `resources` is technically not required but IMHO adds clarity, they should be used only in `handle` (actually `pre/postSupportedCodeSent`).

I agree. I'm not sure that's enough reason to require a change in the request implementations (i.e. the fake and real DMQ nodes), though.

**Comment by gavin-norman-sociomantic** [comment]
I do feel that the abstract class is a reasonable workaround, though, as an intermediary between the current framework and what's coming in swarm v5.1.0.

Can someone summarize the reason for not storing the shared resources in the base class? I didn't get the reasons given above.

**Comment by david-eckardt-sociomantic** [comment]
Well, our request handlers do have a class hierarchy anyway, the fake/real node handler classes are derived from *proto request base classes. Using a mixin instead of the `IRequestHandlerRequest` base class could have caused the same problem.

> Can someone summarize the reason for not storing the shared resources in the base class?

It has a limited scope and can be used only while handling the request. The cleanest way to make this clear is to pass it to a `handle` method as arguments.

**Comment by gavin-norman-sociomantic** [comment]
Ok fair enough. Sorry for the back and forth on this! (This code has been through a pretty confusing sequence of changes recently!)

**Pull request merged**
