### PR TITLE
Test with upstream compilers

### PR DESCRIPTION
**Pull request by mathias-lang-sociomantic**
I have no mean of testing this since I require Swarm v5.x.x to test, but updating DMQ proto is a bit too involved. Any ETA on it @david-eckardt-sociomantic ?
As soon as v14.x.x is compatible with Swarm v5.x.x I'll clean up any remaining issues with upstream compatibility.

### CODE REVIEW

**Comment by david-eckardt-sociomantic** [comment]
I'll complete v14.x.x using Swarm v5.x.x in the next few days, it should be there by Tuesday (maybe even earlier).

**Comment by mathias-lang-sociomantic** [comment]
Alright. Feel free to ping me when it's done, so I can finish to setup the CI to test with upstream.

**Comment by mathias-lang-sociomantic** [comment]
Updated. Turns out we can already enable upstream compatibility!

**Comment by gavin-norman-sociomantic** [comment]
Thanks!

**Pull request merged**
