### PR TITLE
Pass request arguments to notifiers as const

### LINKED ISSUE #25: Pass request parameters to notifier as const
See sociomantic-tsunami/swarm#7.

### PR DESCRIPTION
**Pull request by david-eckardt-sociomantic**
Fixes #25.

### CODE REVIEW

**Review by gavin-norman-sociomantic — APPROVED** [review]

**Comment by gavin-norman-sociomantic** [comment]
(Not a breaking change, as it only modifies unreleased code.)

**Comment by mathias-lang-sociomantic** [comment]
> (Not a breaking change, as it only modifies unreleased code.)

Isn't it ? This target v14.x.x and v14.0.0 has already been released ?

**Comment by gavin-norman-sociomantic** [comment]
The module modified in this PR ( src/dmqproto/client/UsageExamples.d) did not exist in v14.0.0.

**Comment by mathias-lang-sociomantic** [comment]
But `dmqproto.client.request.{Push,Pop,Consume} : Notifier` did. Although a search did not yield any direct usage.

**Comment by gavin-norman-sociomantic** [comment]
Where? https://github.com/sociomantic-tsunami/dmqproto/tree/v14.0.x/src/dmqproto/client

**Comment by mathias-lang-sociomantic** [comment]
Oh, I was looking into David's fork 🤦‍♂️ 
https://github.com/david-eckardt-sociomantic/dmqproto/blob/v13.0.0/src/dmqproto/client/request/Consume.d

**Pull request merged**
