### PR TITLE
Initial import from private repo.

### PR DESCRIPTION
**Pull request by nemanja-boric-sociomantic**
* submodules/makd ()...v1.9.0(0661a59) (1 commits)
  > Deprecate FUN.mapbins in favour of FUN.mapfiles

* submodules/ocean ()...v3.3.1(a991c41) (1 commits)
  > Merge tag v2.9.1 into v3.3.x

* submodules/swarm ()...v4.2.3(f481b6e) (1 commits)
  > Merge tag v3.3.4 into v4.2.x

* submodules/turtle ()...v8.0.0(a319c42) (1 commits)
  > CI with travis and beaver

### CODE REVIEW

**Comment by nemanja-boric-sociomantic** [comment]
Please let me know if this looks all right before merging, so I can turn on the travis testing.

**Comment by gavin-norman-sociomantic** [comment]
LGTM.

**Comment by nemanja-boric-sociomantic** [comment]
Ok, it's green in Travis using 1.080.0.

**Review by leandro-lucarella-sociomantic — APPROVED** [review]
Of course I didn't go through all the imported files, but the changes LGTM

**Pull request merged**
