### PR TITLE
[DO NOT MERGE] Submodule update for v14.x.x

### PR DESCRIPTION
**Pull request by gavin-norman-sociomantic**

### CODE REVIEW

**Comment by gavin-norman-sociomantic** [comment]
The last commit ("Update to makd v2.1.3") causes the `dmqrestart` test to segfault:
```
Program terminated with signal SIGSEGV, Segmentation fault.
#0  fiber_switchContext (oldp=0x7fa21e5b8e60, newp=0x7fa21e5b8c00) at /home/jenkins/docker/src/core/thread.d:2619
2619    /home/jenkins/docker/src/core/thread.d: No such file or directory.
(gdb) bt
#0  fiber_switchContext (oldp=0x7fa21e5b8e60, newp=0x7fa21e5b8c00) at /home/jenkins/docker/src/core/thread.d:2619
Backtrace stopped: Cannot access memory at address 0x7fa31e5b7b30
```
Investigating why...

**Comment by gavin-norman-sociomantic** [comment]
Works with makd v1.10.3.

**Comment by gavin-norman-sociomantic** [comment]
Works with makd up to v1.11.2. Starts failing at v2.0.4.

**Comment by gavin-norman-sociomantic** [comment]
This PR fails on my machine and in Travis, but passes on David's machine. Seems timing related.

**Comment by gavin-norman-sociomantic** [comment]
Updated with simpler version of flaky test.

**Review by david-eckardt-sociomantic — APPROVED** [review]

**Comment by gavin-norman-sociomantic** [comment]
Pushed to v14.x.x.

**Pull request closed without merging**
